baseURL = 'https://bufferb0y.github.io/'
languageCode = 'en-us'
title = 'bufferb0y'
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Me"
  description = "Welcome"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/bufferb0y"

  # Default theme
[params.style]
  darkestColor = "#1a1a1a" # Sidebar - Before 242930
  darkColor = "#0d0d0d" # Background - Before 353b43
  lightColor = "#afbac4" # The text in blog? - Before afbac4 
  lightestColor = "#ffffff" # The title
  primaryColor = "#4d2673" # Purple
